### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by louisJ20** [starryalley/CSC_BLE_Bridge#1]
On my android phone, the app stop brutally. How to do ?

**Comment by starryalley** [comment]
Any logs?

**Comment by louisJ20** [comment]
What do you mean ?

**Comment by starryalley** [comment]
I just pushed something to add more error handling. Please check if this at least makes you able to start the app.

This project is just 2 days old and I've just tested on only 2 Zwift sessions using the same set of hardware written in README. Not much has been tested. Please use with care anyway.

My guess is that your ANT+ dependency might not have been installed? Or BLE isn't supported on your phone? Please install "ANT Tester" from google play. (You should at least see ANT HAL service and ANT Radio service installed.)

For logs, you should be able to gather Android log by https://developer.android.com/studio/debug/bug-report

**Comment by louisJ20** [comment]
> I just pushed something to add more error handling. Please check if this at least makes you able to start the app.
> 
> This project is just 2 days old and I've just tested on only 2 Zwift sessions using the same set of hardware written in README. Not much has been tested. Please use with care anyway.
> 
> My guess is that your ANT+ dependency might not have been installed? Or BLE isn't supported on your phone? Please install "ANT Tester" from google play. (You should at least see ANT HAL service and ANT Radio service installed.)
> 
> For logs, you should be able to gather Android log by https://developer.android.com/studio/debug/bug-report

Nothing works. My laptop is on android 7, compatible with ant + connectivity.

When I press "Start Service" the application stop brutaly.

I've been trying to find an app like this for days. I hope I can do it.

**Comment by starryalley** [comment]
Interesting setup. Can you at least take the bug report so I can take a look? Nothing can be done by saying it crashes.

**Comment by louisJ20** [comment]
> Interesting setup. Can you at least take the bug report so I can take a look? Nothing can be done by saying it crashes.

To capture it is necessary that I launch a capture at the same time as the application crashes?

**Comment by starryalley** [comment]
No, you can take it right after it crashes. 

My guess is that it is not compatible with Android 7 since I've set the min supported API=26, which is Android 8.0. I used something which is only on Android 8.0. Sorry about it. I can find some time to support older Android versions but not today.

**Comment by louisJ20** [comment]
Ok. I changed in android studio the mindsdk. But nothing work in my phone. I suggest that it's not the only problem.

How to share you the bug report ?

**Comment by starryalley** [comment]
It won't work by just changing the min SDK because it uses features found in newer Android version. You will need to change the way I write it to make it support older Android version.

You can share the bug report anywhere you like, for example, a google drive link or dropbox link and give the link here.

**Comment by starryalley** [comment]
I just pushed a possible fix to support API 24 (Android 7.0): https://github.com/starryalley/CSC_BLE_Bridge/tree/supports_api_24

I've tested on my Android 7.1, 8.1 and 9.0 devices without problem. However my Android 7.0 and 8.1 devices don't support ANT+ so I can only be sure it at least starts. That's it for now. I'm off to ride on Zwift.

**Comment by louisJ20** [comment]
Thank you it works wonderfully. My brother has an android 4. Is it possible to have it for this version too?

**Comment by starryalley** [comment]
@louisJ20 glad to hear it works for you! Can you let me know your Android device (brand and type?) and ANT+ speed/cadence sensor brand, so I can list in the README as tested? 

For Android 4 support I believe it's much more work. I've opened #2 for tracking.

**Comment by louisJ20** [comment]
The phone is Samsung galaxy J5 2016. And my sensors are the 1st generation of Garmin sensor ant+.

**Comment by starryalley** [comment]
Thanks. Closing this one and track in #2.
