### ISSUE TITLE
Galaxy s4 i9505 - no BLE advertised

### ISSUE THREAD

**Issue by chrismonks** [starryalley/CSC_BLE_Bridge#15]
Hi,
Firstly great app. It will save me alot of headaches when i finally get it working.

So I got ANt+ working on my old s4 stock android 5 rom. The csc app see's me speed/cadence/HR devices and reports correct.

But, there it does not advertise a BTLE device that I can use on zwitft or anything else. 

I tried changing device name to only "S4". Bluetooth is working and I've testing sharing within the bluetooth settings and my other devices can see it.

logcat doesn't give me much, and I can't see the "advertising log" as discussed in the Nexus 5 thread.
Anyone any thoughts on how to debug

Logcat:
`V/ActivityThread( 8656): updateVisibility : ActivityRecord{134a8496 token=android.os.BinderProxy@28d13336 {idv.markkuo.cscblebridge/idv.markkuo.cscblebridge.MainActivity}} show : true
V/ActivityThread( 8656): updateVisibility : ActivityRecord{134a8496 token=android.os.BinderProxy@28d13336 {idv.markkuo.cscblebridge/idv.markkuo.cscblebridge.MainActivity}} show : false
I/Timeline( 1398): Timeline: Activity_launch_request id:idv.markkuo.cscblebridge time:422439
I/ActivityManager(  820): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=idv.markkuo.cscblebridge/.MainActivity bnds=[8,780][263,1110]} from uid 10008 on display 0
I/Timeline(  820): Timeline: Activity_windows_visible id: ActivityRecord{268aeefa u0 idv.markkuo.cscblebridge/.MainActivity t78} time:422849
V/ActivityThread( 8656): updateVisibility : ActivityRecord{134a8496 token=android.os.BinderProxy@28d13336 {idv.markkuo.cscblebridge/idv.markkuo.cscblebridge.MainActivity}} show : false
I/Timeline( 1398): Timeline: Activity_launch_request id:idv.markkuo.cscblebridge time:503879
I/ActivityManager(  820): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=idv.markkuo.cscblebridge/.MainActivity bnds=[8,780][263,1110]} from uid 10008 on display 0
I/Timeline(  820): Timeline: Activity_windows_visible id: ActivityRecord{268aeefa u0 idv.markkuo.cscblebridge/.MainActivity t78} time:504296
V/ActivityThread( 8656): updateVisibility : ActivityRecord{134a8496 token=android.os.BinderProxy@28d13336 {idv.markkuo.cscblebridge/idv.markkuo.cscblebridge.MainActivity}} show : true

V/ActivityThread( 8656): updateVisibility : ActivityRecord{134a8496 token=android.os.BinderProxy@28d13336 {idv.markkuo.cscblebridge/idv.markkuo.cscblebridge.MainActivity}} show : true
V/ActivityThread( 8656): updateVisibility : ActivityRecord{134a8496 token=android.os.BinderProxy@28d13336 {idv.markkuo.cscblebridge/idv.markkuo.cscblebridge.MainActivity}} show : false
I/Timeline( 1398): Timeline: Activity_launch_request id:idv.markkuo.cscblebridge time:1336160
I/ActivityManager(  820): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=idv.markkuo.cscblebridge/.MainActivity bnds=[8,780][263,1110]} from uid 10008 on display 0
I/Timeline(  820): Timeline: Activity_windows_visible id: ActivityRecord{268aeefa u0 idv.markkuo.cscblebridge/.MainActivity t78} time:1336575
V/ActivityThread( 8656): updateVisibility : ActivityRecord{134a8496 token=android.os.BinderProxy@28d13336 {idv.markkuo.cscblebridge/idv.markkuo.cscblebridge.MainActivity}} show : true
V/ActivityThread( 8656): updateVisibility : ActivityRecord{134a8496 token=android.os.BinderProxy@28d13336 {idv.markkuo.cscblebridge/idv.markkuo.cscblebridge.MainActivity}} show : false
I/VlingoApplication(14458): VlingoApplication appVersion ='11.2.2.0.37993', ro.csc.sales_code=BTU
D/ResourcesManager( 1562): creating new AssetManager and set to /data/app/idv.markkuo.cscblebridge-1/base.apk
D/UsbSettingsManager(  820): hasDefaults: idv.markkuo.cscblebridge FALSE
V/ApplicationPolicy(  820): isApplicationStateBlocked userId 0 pkgname idv.markkuo.cscblebridge
I/ActivityManager(  820): Force stopping idv.markkuo.cscblebridge appid=10205 user=0: from pid 1562
I/ActivityManager(  820): Killing 8656:idv.markkuo.cscblebridge/u0a205 (adj 2): stop idv.markkuo.cscblebridge
W/ActivityManager(  820): Scheduling restart of crashed service idv.markkuo.cscblebridge/.CSCService in 1000ms
I/ActivityManager(  820):   Force finishing activity ActivityRecord{268aeefa u0 idv.markkuo.cscblebridge/.MainActivity t78}
D/UsbSettingsManager(  820): hasDefaults: idv.markkuo.cscblebridge FALSE
I/Timeline( 1398): Timeline: Activity_launch_request id:idv.markkuo.cscblebridge time:1479736
V/ApplicationPolicy(  820): isApplicationStateBlocked userId 0 pkgname idv.markkuo.cscblebridge
I/ActivityManager(  820): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=idv.markkuo.cscblebridge/.MainActivity bnds=[8,780][263,1110]} from uid 10008 on display 0
I/ActivityManager(  820): Start proc idv.markkuo.cscblebridge for activity idv.markkuo.cscblebridge/.MainActivity: pid=15351 uid=10205 gids={50205, 9997, 3003, 3002, 3001} abi=armeabi-v7a
D/ResourcesManager(15351): creating new AssetManager and set to /data/app/idv.markkuo.cscblebridge-1/base.apk
D/ResourcesManager(15351): creating new AssetManager and set to /data/app/idv.markkuo.cscblebridge-1/base.apk
I/ActivityManager(  820): Displayed idv.markkuo.cscblebridge/.MainActivity: +659ms
I/Timeline(  820): Timeline: Activity_windows_visible id: ActivityRecord{1ecd617b u0 idv.markkuo.cscblebridge/.MainActivity t82} time:1480416
V/ActivityThread(15351): updateVisibility : ActivityRecord{14b1f217 token=android.os.BinderProxy@28d13336 {idv.markkuo.cscblebridge/idv.markkuo.cscblebridge.MainActivity}} show : false
I/Timeline( 1398): Timeline: Activity_launch_request id:idv.markkuo.cscblebridge time:1645620
I/ActivityManager(  820): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=idv.markkuo.cscblebridge/.MainActivity bnds=[8,780][263,1110]} from uid 10008 on display 0
I/Timeline(  820): Timeline: Activity_windows_visible id: ActivityRecord{1ecd617b u0 idv.markkuo.cscblebridge/.MainActivity t82} time:1646017
V/ActivityThread(15351): updateVisibility : ActivityRecord{14b1f217 token=android.os.BinderProxy@28d13336 {idv.markkuo.cscblebridge/idv.markkuo.cscblebridge.MainActivity}} show : false
I/Timeline( 1398): Timeline: Activity_launch_request id:idv.markkuo.cscblebridge time:1962490
I/ActivityManager(  820): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=idv.markkuo.cscblebridge/.MainActivity bnds=[8,780][263,1110]} from uid 10008 on display 0
I/Timeline(  820): Timeline: Activity_windows_visible id: ActivityRecord{1ecd617b u0 idv.markkuo.cscblebridge/.MainActivity t82} time:1962896
V/ActivityThread(15351): updateVisibility : ActivityRecord{14b1f217 token=android.os.BinderProxy@28d13336 {idv.markkuo.cscblebridge/idv.markkuo.cscblebridge.MainActivity}} show : false
`

**Comment by chrismonks** [comment]
hmmm, 
verbose logs show
W/CSCService(25351): Failed to create advertiser

**Comment by starryalley** [comment]
Glad that you find it useful. Unfortunately that failure log may have explained why: 

> getBluetoothLeAdvertiser () Will return null if Bluetooth is turned off or if Bluetooth LE Advertising is not supported on this device.
[API doc link here](https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#getBluetoothLeAdvertiser())

**Comment by chrismonks** [comment]
ouch. my dreams go up in flames.
Have to search the place now for another device with possible support.
Thanks for the support

**Comment by chrismonks** [comment]
Here is a good list of device that support advertise 
https://altbeacon.github.io/android-beacon-library/beacon-transmitter-devices.html

**Comment by chrismonks** [comment]
works on Samsung Galaxy a40 & Nokia 5.3
