### ISSUE TITLE
Muiltiple Activity Instances

### ISSUE THREAD

**Issue by Gaudon** [starryalley/CSC_BLE_Bridge#18]
Great project, really helped me out when relaying my ant+ only garmin watch to link with Zwift!

I've noticed 2 issues as of late.

1. When minimizing the app to run as a service in the notification shade, resuming the activity often launches a new activity. This requires pressing back multiple times to get to the "active" activity that's actually enabled and transmitting information.
2. Sometimes the app crashes on startup and becomes unresponsive. The only way to fix this I've seen is to uninstall and reinstall it. I haven't tried clearing app data yet, but it shouldn't be necessary.

This is done on a Samsung Galaxy S9 running Android 10.

**Comment by starryalley** [comment]
Thanks for the bug report. I did notice issue 1 myself but haven't seen issue 2 yet on my Samsung S8. 

I haven't been riding on zwift lately (got a newborn in the house) so I haven't used this app in the past 2 or 3 months. I'll see what I can do to get this fixed when I have the time!

**Comment by Gaudon** [comment]
Thanks for the quick reply! I'm a software engineer myself, and thought about taking on a very similar project before finding this one. If I get a chance I'll look through the code, I have done some android development but it's not my area of expertise. If it looks obvious I'll just open a PR. 

Cheers!

**Comment by Gaudon** [comment]
![Screenshot_20210207-221456_CSC BLE Bridge](https://user-images.githubusercontent.com/1593839/107166972-27466a80-6992-11eb-9f6c-29a1c383a5cb.jpg)

![Screenshot_20210207-221456_CSC BLE Bridge](https://user-images.githubusercontent.com/1593839/107166983-2f060f00-6992-11eb-8612-6f01e1e8ba24.jpg)

**Comment by Gaudon** [comment]
![Screenshot_20210207-221354_CSC BLE Bridge](https://user-images.githubusercontent.com/1593839/107167109-8e641f00-6992-11eb-9a9e-560a72bfc4b9.jpg)

**Comment by ebiga** [comment]
I can confirm bug 2 and cleaning app data/cache nor even restarting helps. App gets unresponsive.
It worked for a couple of times before current status in which it cannot be used. I didn't try reinstalling.
If there's any log file you want me to share, please let me know.

**Comment by michaelrhughes** [comment]
I ran into a similar issue when working on https://github.com/starryalley/CSC_BLE_Bridge/pull/20. I changed the communication to bind to the service and send messages along with a change to `singleInstance` for the activity. This way the Activity always binds to the service and gets the latest state from the service.

**Comment by DJJo14** [comment]
#20 is now merge in the master. Can there come a new release?

**Comment by starryalley** [comment]
Thanks @DJJo14. That awesome PR #20 indeed deserves a new release. Sorry I haven't worked on this for a long time. 
I've just released v1.3 [here](https://github.com/starryalley/CSC_BLE_Bridge/releases/tag/v1.3)

**Comment by starryalley** [comment]
Closing as the latest v1.3.x release should have resolved this issue. Please reopen if not.
