### ISSUE TITLE
Support older Android

### ISSUE THREAD

**Issue by starryalley** [starryalley/CSC_BLE_Bridge#2]
Bluetooth LE: Android 4.3 (API level 18) 

See if it's possible to support older android version.

See #1

**Comment by louisJ20** [comment]
I don't know if you changed something for android 4 but it still doesn't work. Android studio tells me that the mindsk is at 19.

**Comment by starryalley** [comment]
No I haven't done anything yet.

Unfortunately I took a look at the main package which advertises the phone as a Bluetooth LE device, the minimal supported version is API 21 (Android 5.0 Lollipop):
https://developer.android.com/reference/android/bluetooth/le/package-summary

It is impossible to support Android 4.4 Kitkat (API 19). You will at least need a ANT+ BLE enabled Android 5.0 devices to run this app.

This issue will then be focus on supporting API 21.
