### ISSUE TITLE
HR Sensor not detected

### ISSUE THREAD

**Issue by CS-Biker** [starryalley/CSC_BLE_Bridge#23]
Hello.
The CSC BLE Bridge does not recognize my heart rate Sensor, allthough all required dependencies (ANT Radio Service and ANT+ Plugins Service) are installed.
Other bike apps (e.g. Jepster) immediately show the transferred heart rate. So ANT+ is basically working.
Any ideas how to solve this problem?
I'm trying to run the app on a Samsung S10 with Android 11.
Any help is appreciated.
With kind regards

**Comment by starryalley** [comment]
Hi @CS-Biker thanks for reporting the issue. 

Is your heart rate sensor listed in [readme](https://github.com/starryalley/CSC_BLE_Bridge#readme) ? I see Samsung S10 has complete ANT+ support so this app should work. Any chance you have other ANT+ sensors (not limited to heart rate sensors) to test with? 

Also I've just released v1.3 which has some fix by a great contributor. Maybe you can test again with v1.3. Thank you.

**Comment by starryalley** [comment]
Thanks for the info. However it will be a tricky one as I don't have the exact phone as you have. However I just tested with my Fenix 6 broadcasting heart rate to my Samsung S8 running version 1.3 of this app and it worked right away and Zwift can read my wrist heart rate from Fenix 6. 

The other app can read from your 2 ANT+ sensors did indicate there could be something wrong with this app. Any chance that you can start the app, and try what you tried again for 1-3min, and then do a full bug report from Settings->Developer options->Bug report and attach here? Thank you.

**Comment by CS-Biker** [comment]
Hi,

Not knowing, whether the bug report contains sensitiv information and data, I would prefer not to upload the 27MB zip file into github.

Do you have any temporary cloud drive I can copy the bug report to?

Thanks for your support so far.

Cheers,
Chris

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by starryalley** [comment]
Hi @CS-Biker that makes sense. Can you please upload to your google drive or dropbox or similar free service, and share via link and send the link privately to me (starryalley at gmail dot com) ? Once I download it I'll let you know so you can delete it online permanently. Thank you.

**Comment by starryalley** [comment]
Hi @CS-Biker I'm able to download your bugreport zip and this is what I found:
```
01-18 11:00:18.889 10483 30862 30862 E AntPluginPcc: BBD30800: Unable to configure logging, plugins package not found: android.content.pm.PackageManager$NameNotFoundException: Application package com.dsi.ant.plugins.antplus not found
...
01-18 11:00:18.899 10483 30862 30862 E AntPluginPcc: BBD30800: Binding to plugin failed, not installed
...
01-18 11:00:18.948 10483 30862 30862 W AntPluginPcc: BBD30800: RequestAccess failed: Missing Dependency: com.dsi.ant.plugins.antplus not installed.
01-18 11:00:18.949 10483 30862 30862 W AntDeviceManager: Ant Device State changed: DEAD, resultCode: DEPENDENCY_NOT_INSTALLED
```

Since I'm sure you must have already installed all the ANT+ dependencies, it could be that CSC BLE Bridge app can't find it even if it is installed. Then I came across [this article where the author fixed a similar issue](https://rickyvanrijn.nl/2020/12/30/android-app-with-ant/)

It could be due to Android 11 [package visibility filtering](https://developer.android.com/training/package-visibility)

I've built an apk (please unzip first) with the proposed fix from the author. Can you give it a try? Thank you.
[app-release.apk.zip](https://github.com/starryalley/CSC_BLE_Bridge/files/7895890/app-release.apk.zip)

**Comment by CS-Biker** [comment]
Hi Mark,

That fix solved the problem.
The heart rate sent from the Fenix 5 is now picked up by your CSC BLE Bridge and transmitted via Bluetooth.

Again, really appreciated your support and thank you very much for fixing the problem instantly.

Best regards,
Chris


________________________________

**Comment by starryalley** [comment]
Glad to hear that! Also thank you for helping me debug this!
