### ISSUE TITLE
Compatible with an other Garmin sensor

### ISSUE THREAD

**Issue by louisJ20** [starryalley/CSC_BLE_Bridge#3]
Hello,

I tested your app with an other version of Garmin sensor. It's the sensor cadence/speed together.
With this your app is functional.
<img width="459" alt="Capture d’écran 2020-04-29 à 21 16 50" src="https://user-images.githubusercontent.com/56971289/80637106-bf581080-8a5e-11ea-8102-9125242fc868.png">

I have an other sensor to test. I'll keep you informed.

**Comment by starryalley** [comment]
Thanks for testing that!

**Comment by starryalley** [comment]
From ANT official website I can only find this one made by Garmin, could be the same one you tested:
https://www.thisisant.com/directory/gsc-10-speed-cadence-bike-sensor

**Comment by ecammit** [comment]
I tested the GSC-10 with my Samsung S9. Unfortunately it either registers the speed or the cadence... not both. I'll see if I can debug it and issue a pull request.

I also tested this with a Garmin Vivoactive 4 watch set to broadcast a heart rate. It works.

**Comment by starryalley** [comment]
Thanks @ecammit !

**Comment by ecammit** [comment]
Pull request #8

**Comment by ecammit** [comment]
![Screenshot_20201119-210235_CSC BLE Bridge](https://user-images.githubusercontent.com/729933/99749781-1f6edc80-2aad-11eb-85ba-16476355462e.jpg)

**Comment by starryalley** [comment]
Pull request #8 has been merged. Closing.
